"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.useIsWindowActive = exports.useElementVisibility = exports.useDebounce = exports.useThrottle = exports.useClipboard = exports.useTimeout = exports.useInterval = exports.usePeriodicTime = exports.useOutsideClick = exports.useWindowSize = exports.useOnResize = exports.useWindowEvent = exports.useCountDown = exports.useOnEsc = exports.useKeyListener = exports.useResizeObserver = void 0;
const useResizeObserver_1 = __importDefault(require("./hooks/useResizeObserver"));
exports.useResizeObserver = useResizeObserver_1.default;
const useKeyListener_1 = __importDefault(require("./hooks/useKeyListener"));
exports.useKeyListener = useKeyListener_1.default;
const useOnEsc_1 = __importDefault(require("./hooks/useOnEsc"));
exports.useOnEsc = useOnEsc_1.default;
const useCountDown_1 = __importDefault(require("./hooks/useCountDown"));
exports.useCountDown = useCountDown_1.default;
const useWindowEvent_1 = __importDefault(require("./hooks/useWindowEvent"));
exports.useWindowEvent = useWindowEvent_1.default;
const useOnResize_1 = __importDefault(require("./hooks/useOnResize"));
exports.useOnResize = useOnResize_1.default;
const useWindowSize_1 = __importDefault(require("./hooks/useWindowSize"));
exports.useWindowSize = useWindowSize_1.default;
const useOutsideClick_1 = __importDefault(require("./hooks/useOutsideClick"));
exports.useOutsideClick = useOutsideClick_1.default;
const usePeriodicTime_1 = __importDefault(require("./hooks/usePeriodicTime"));
exports.usePeriodicTime = usePeriodicTime_1.default;
const useInterval_1 = __importDefault(require("./hooks/useInterval"));
exports.useInterval = useInterval_1.default;
const useTimeout_1 = __importDefault(require("./hooks/useTimeout"));
exports.useTimeout = useTimeout_1.default;
const useClipboard_1 = __importDefault(require("./hooks/useClipboard"));
exports.useClipboard = useClipboard_1.default;
const useThrottle_1 = __importDefault(require("./hooks/useThrottle"));
exports.useThrottle = useThrottle_1.default;
const useDebounce_1 = __importDefault(require("./hooks/useDebounce"));
exports.useDebounce = useDebounce_1.default;
const useElementVisibility_1 = __importDefault(require("./hooks/useElementVisibility"));
exports.useElementVisibility = useElementVisibility_1.default;
const useIsWindowActive_1 = __importDefault(require("./hooks/useIsWindowActive"));
exports.useIsWindowActive = useIsWindowActive_1.default;
//# sourceMappingURL=index.js.map